# Generated by Django 6.1 on 2026-08-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=5)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
